export default interface ILibraryBook {
    id: number,
    Author: string,
    EBookPath: string,
    DateCreated: string,
    IsCD: number,
    IsGift: number,
    IsOut: number,
    LLC: string,
    Language: string,
    MONRecomended: string,
    NameRuBook: string,
    Pages: string,
    PublishedCountryCity: string,
    PublishedTime: string,
    PublishingHouse: string,
    RLibraryCategoryRLibraryBook: number,
    Subject: string,
    TypeOfBook: string,
    UDC: string,
    bookcat: string,
}  